rb_carnet_home:
    path:     /
    defaults: { _controller: RBCarnetBundle:Carnet:index }

rb_carnet_ajout_eleve:
    path:     /ajoutEleve
    defaults: { _controller: RBCarnetBundle:Carnet:ajoutEleve }

rb_carnet_modif_eleve:
    path:     /modifEleve/{id}
    defaults: { _controller: RBCarnetBundle:Carnet:modifEleve }
    requirements:
        id: \d+

rb_carnet_supprime_eleve:
    path:     /supprimeEleve/{id}
    defaults: { _controller: RBCarnetBundle:Carnet:supprimeEleve }
    requirements:
        id: \d+

rb_carnet_ajout_note:
    path:     /ajoutNote/{id}
    defaults: { _controller: RBCarnetBundle:Carnet:ajoutNote }
    requirements:
        id: \d+
